default['httpd']['html_dir']      = '/var/www/html'
default['httpd']['package_name']  = 'httpd'
default['httpd']['service_name']  = 'httpd'
default['httpd']['user']          = 'apache'
default['httpd']['group']          = 'apache'
